### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by WadrianAraujo** [yanpaing007/binance-moonbix-bot#2]
where to find the bot iframe url

I can't find it

**Comment by yanpaing007** [comment]
![image](https://github.com/user-attachments/assets/2a08b01a-4b36-482c-9160-98b04e3c7eaf)
copy every inside src="" that is your url

**Comment by WadrianAraujo** [comment]
are you using web telegram? the game only works with the windows telegram app in my case

![image](https://github.com/user-attachments/assets/edb3afdd-912d-4f73-bb67-1510864301dd)

**Comment by yanpaing007** [comment]
https://chromewebstore.google.com/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe install this extension and reload the bot

**Comment by yanpaing007** [comment]
You can also do right click on that white page and click view frame source ,and copy your url

**Comment by WadrianAraujo** [comment]
Thank you very much, it worked perfectly
